using System;
using System.Collections.Generic;
using System.Text;

namespace PoEW.Data.Enums {
    public enum CurrencyType {
        CURRENCY_NONE,
        CURRENCY_ORB_OF_ALTERATION,
        CURRENCY_ORB_OF_FUSING,
        CURRENCY_ORB_OF_ALCHEMY,
        CURRENCY_CHAOS_ORB,
        CURRENCY_GCP,
        CURRENCY_EXALTED_ORB,
        CURRENCY_CHROMATIC_ORB,
        CURRENCY_JEWELLERS_ORB,
        CURRENCY_ORB_OF_CHANCE,
        CURRENCY_CARTOGRAPHERS_CHISEL,
        CURRENCY_ORB_OF_SCOURING,
        CURRENCY_BLESSED_ORB,
        CURRENCY_ORB_OF_REGRET,
        CURRENCY_REGAL_ORB,
        CURRENCY_DIVINE_ORB,
        CURRENCY_VAAL_ORB,
        CURRENCY_PERANDUS_COIN,
        CURRENCY_MIRROR_OF_KALANDRA,
        CURRENCY_SILVER_COIN,
    }
}
